name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: nerdyhick
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: nerdyhick/garak-repo
        tags: |
          type=raw,value=0.0.${{ github.run_number }}
          type=raw,value=latest
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{ github.run_number }}
        release_name: Release v0.0.${{ github.run_number }}
        body: |
          ## Docker Image Available
          
          This release includes a Docker image for easy deployment.
          
          ### Pull the image:
          ```bash
          docker pull nerdyhick/garak-repo:0.0.${{ github.run_number }}
          ```
          
          ### Run the container:
          ```bash
          docker run -p 3000:3000 -v /path/to/your/reports:/app/data nerdyhick/garak-repo:0.0.${{ github.run_number }}
          ```
          
          ### Run in detached mode:
          ```bash
          docker run -d -p 3000:3000 \
            -v /path/to/your/reports:/app/data \
            --name garak-repo \
            nerdyhick/garak-repo:0.0.${{ github.run_number }}
          ```
          
          **Note:** Replace `/path/to/your/reports` with the actual path to your Garak report files.
          
          ### Latest version:
          You can also use the `latest` tag:
          ```bash
          docker pull nerdyhick/garak-repo:latest
          docker run -p 3000:3000 -v /path/to/your/reports:/app/data nerdyhick/garak-repo:latest
          ```
        draft: false
        prerelease: false
